Gestion de publications: tx_ligestpublications_pi1 Class Reference
tx_ligestpublications_pi1 Class Reference
Public Member Functions
main ($content, $conf)
Data Fields
$prefixId = 'tx_ligestpublications_pi1'
$scriptRelPath = 'pi1/class.tx_ligestpublications_pi1.php'
$extKey = 'li_gest_publications'
$pi_checkCHash = true
Private Member Functions
rechercheFils ($pid_parent)
rechercherUidLangue ($uid, $sys_language_uid, $uid_parent, $texte_champ, $table, $nom_champ)
equipe ($uid_equipes)
membre ($uid_membres)
auteur ($uid_auteurs)
theme ($uid_themes)
type ($uid_types)
Detailed Description
Definition at line 35 of file class.tx_ligestpublications_pi1.php.
Member Function Documentation
auteur ($ uid_auteurs) [private]
Choix des auteurs Cette fonction permet de créer une contrainte concernant les auteurs
Parameters:
$equipe Chaîne de caractères contenant les identifiants des auteurs(uid) séparés par des virgules
Returns:
Une chaîne de caratères contenant une contrainte à rajouter à une requête
Definition at line 244 of file class.tx_ligestpublications_pi1.php.
Referenced by main().
equipe ($ uid_equipes) [private]
Choix de l'équipe Cette fonction permet de créer une contrainte concernant les équipes
Parameters:
$equipe Chaîne de caractères contenant les identifiants des équipes(uid) séparés par des virgules
Returns:
Une chaîne de caratères contenant une contrainte à rajouter à une requête
Definition at line 165 of file class.tx_ligestpublications_pi1.php.
Referenced by main().
main ($ content, $ conf)
The main method of the PlugIn
Parameters:
string $content: The PlugIn content
array $conf: The PlugIn configuration
Returns:
The content that is displayed on the website
Definition at line 365 of file class.tx_ligestpublications_pi1.php.
References auteur(), equipe(), membre(), rechercheFils(), rechercherUidLangue(), theme(), and type().
membre ($ uid_membres) [private]
Choix des membres Cette fonction permet de créer une contrainte concernant les membres
Parameters:
$equipe Chaîne de caractères contenant les identifiants des membres(uid) séparés par des virgules
Returns:
Une chaîne de caratères contenant une contrainte à rajouter à une requête
Definition at line 204 of file class.tx_ligestpublications_pi1.php.
Referenced by main().
rechercheFils ($ pid_parent) [private]
Recherche des sous-dossiers contenant les membres du laboratoire...
Parameters:
$pid_parent identifiant du dossier à explorer
Returns:
Un tableau contenant tous les sous-dossiers trouvés...
Definition at line 47 of file class.tx_ligestpublications_pi1.php.
Referenced by main().
rechercherUidLangue ($ uid, $ sys_language_uid, $ uid_parent, $ texte_champ, $ table, $ nom_champ) [private]
Gestion du multilangue Cette fonction recherche le texte le plus approprié par rapport à la page chargée Cette fonction est utilisée à la suite d'une requête permettant de connaître les paramètres $uid, $sys_language_uid, $uid_parent et $texte_champ.
Parameters:
$uid L'identifiant de l'enregistrement pour lequel on recherche la meilleur traduction.
$sys_language_uid L'identifiant de la langue de l'enregistrement pour lequel on recherche la meilleur traduction.
$uid_parent L'identifiant du parent de l'enregistrement pour lequel on recherche la meilleur traduction.
$texte_champ La traduction de l'enregistrement pour lequel on recherche la meilleur traduction.
$table Le nom de la table dans laquel se trouve le champ à traduire
$nom_champ Le nom du champ à traduire
Returns:
Une chaîne de caratères contenant la traduction a afficher
Definition at line 96 of file class.tx_ligestpublications_pi1.php.
Referenced by main().
theme ($ uid_themes) [private]
Choix des themes Cette fonction permet de créer une contrainte concernant les themes
Parameters:
$equipe Chaîne de caractères contenant les identifiants des themes(uid) séparés par des virgules
Returns:
Une chaîne de caratères contenant une contrainte à rajouter à une requête
Definition at line 284 of file class.tx_ligestpublications_pi1.php.
Referenced by main().
type ($ uid_types) [private]
Choix des types de publications Cette fonction permet de créer une contrainte concernant les types de publications
Parameters:
$equipe Chaîne de caractères contenant les identifiants des types de publications(uid) séparés par des virgules
Returns:
Une chaîne de caratères contenant une contrainte à rajouter à une requête
Definition at line 323 of file class.tx_ligestpublications_pi1.php.
Referenced by main().
Field Documentation
$extKey = 'li_gest_publications'
Definition at line 38 of file class.tx_ligestpublications_pi1.php.
$pi_checkCHash = true
Definition at line 39 of file class.tx_ligestpublications_pi1.php.
$prefixId = 'tx_ligestpublications_pi1'
Definition at line 36 of file class.tx_ligestpublications_pi1.php.
$scriptRelPath = 'pi1/class.tx_ligestpublications_pi1.php'
Definition at line 37 of file class.tx_ligestpublications_pi1.php.
The documentation for this class was generated from the following file:
C:/Documents and Settings/Peguy/Bureau/PFE2/li_gest_publications/pi1/class.tx_ligestpublications_pi1.php